name: 'gh program downloader'
description: 'Download a release'
inputs:
  repository:
    description:
    required: false
  destination:
    description:
    required: false
  file-re:
    description:
    required: false
  trace:
    description:
    required: false
runs:
  using: "composite"
  steps:
  - name: Run downloader
    uses: check-spelling/gh-program-downloader@5e540d58810c8d629cacba3e43dc9cc5c44ccf06 # v0.0.4 + 6 commits
    with:
      repository: ${{ inputs.repository }}
      destination: ${{ inputs.destination }}
      file-re: ${{ inputs.file-re }}
      trace: ${{ inputs.trace }}
