name: 'gh program downloader'
description: 'Download a release'
inputs:
  repository:
    description:
    required: false
  destination:
    description:
    required: false
  file-re:
    description:
    required: false
  trace:
    description:
    required: false
runs:
  using: "composite"
  steps:
  - name: Run downloader
    uses: check-spelling/gh-program-downloader@4a039853fb716e1a2696fa8d09974b8ac6653905 # v0.0.1
    with:
      repository: ${{ inputs.repository }}
      destination: ${{ inputs.destination }}
      file-re: ${{ inputs.file-re }}
      trace: ${{ inputs.trace }}
