name: 'gh program downloader'
description: 'Download a release'
inputs:
  repository:
    description:
    required: false
  destination:
    description:
    required: false
  file-re:
    description:
    required: false
  trace:
    description:
    required: false
runs:
  using: "composite"
  steps:
  - name: Run downloader
    uses: check-spelling/gh-program-downloader@c6f28a25b2cbfd91693af602ed712328f4e97552 # v0.0.4 + 1 commit
    with:
      repository: ${{ inputs.repository }}
      destination: ${{ inputs.destination }}
      file-re: ${{ inputs.file-re }}
      trace: ${{ inputs.trace }}
