# powerdns/pdns master=0b94d1e43fa2447935bec969699893f3218d593c
# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
# spelling2.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-p8r9-69g4-jwqq
name: Spell checking (powerdns/pdns)

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  spelling:
    name: Spell checking
    permissions:
      # contents-read is needed to checkout in private repositories
      contents: read
      # pull-requests-read is needed for suppress_push_for_open_pull_request in private repositories
      pull-requests: read
      # actions-read is needed (possibly only for private repositories)
      # to identify the workflow's filename until
      # https://github.com/actions/runner/issues/853 is fixed
      actions: read
      # security-events-write is needed according to the documentation:
      # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: powerdns/pdns
      - name: shim
        shell: bash
        run: |
          echo '^README\.md$' > .github/actions/spell-check/only.txt
          git add -u
          git config --global user.email "user@example.com"
          git config --global user.name "user"
          git commit -m 'Skip everyone else'
      - name: check-spelling
        id: spelling
        uses: check-spelling-sandbox/check-spelling@prerelease
        with:
          config: .github/actions/spell-check
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
          checkout: false
          check_file_names: 1
          spell_check_this: powerdns/pdns@master
          post_comment: 0
          use_magic_file: 1
          warnings: bad-regex,binary-file,deprecated-feature,ignored-expect-variant,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check,unclosed-block-ignore-begin,unclosed-block-ignore-end
          use_sarif: ${{ (!github.event.pull_request || (github.event.pull_request.head.repo.full_name == github.repository)) && 1 }}
          extra_dictionaries: |
            cspell:software-terms/dict/softwareTerms.txt
            cspell:html/dict/html.txt
          check_extra_dictionaries:
            cspell:no-such-dictionary.txt
          debug: 1
